### ISSUE TITLE
学校安全调整，需要使用VPN访问学工系统

### ISSUE THREAD

**Issue by Hell-Tractor** [kirainmoe/auto-daily-health-report#12]
据通知，6月3日起校外访问学工系统进行健康打卡需要连接vpn。

而VPN登录又需要用到[企业微信登录](https://open.work.weixin.qq.com/wwopen/mpnews?mixuin=zdCnDQAABwB7HS1PAAAUAA&mfid=WW0305-MbyB5QAABwCBWYpWLBj5NAwUdgs65&idx=0&sn=60fa72b001663906c6da6a7a59e3b335)

**Comment by kirainmoe** [comment]
感谢反馈，但目前深信服的 EasyConnect 只能通过企业微信扫码登录，而企业微信的登录方式无法通过代码层面直接模拟。因此建议你在电脑或服务器上挂 VPN 进行打卡。

以 Linux 服务器为例，可以安装 Docker 并使用 https://github.com/Hagb/docker-easyconnect 项目起一个 7.6.7 的 VPN 客户端，用 VNC 客户端连接并使用企业微信扫码登录，该容器会向外暴露一个 127.0.0.1:8888 的 HTTP 代理，再使用这个 HTTP 代理运行本项目即可：

```
export HTTP_PROXY=127.0.0.1:8888 
export HTTPS_PROXY=127.0.0.1:8888 
xmu-health-report-rust-sdk ...
```

或者，如果你的 Linux 服务器安装了图形界面，也可以直接安装官方版 EasyConnect 并扫码登录，这样会直接在你的 Linux 服务器上创建一个虚拟网卡设备将所有厦大的 IP 导流到此网卡上，无需配置 HTTP 代理。
