### ISSUE TITLE
希望可以加一个当前在校状态字段

### ISSUE THREAD

**Issue by jhyscode** [kirainmoe/auto-daily-health-report#2]
学校打卡系统页面已经更改，新增当前在校状态，包括在校和不在校的选项，希望楼主可以在Post构造的数据中加一下。

**Comment by kirainmoe** [comment]
当前在校和当前所在地理位置会自动继承昨日的数据，也就是说只要你手动在学工系统填写一次，往后都不需要再手动修改这两项，而仍然只需要勾选承诺即可。因此不增加这两个字段，程序也可以正常打卡。

**Comment by jhyscode** [comment]
好的，感谢大佬的回复和开源分享！

**Comment by iscas-glm** [comment]
git clone到centos7服务器上好像login.py  21行要改成 with open("./encrypt.js", "r") as file:

**Comment by kirainmoe** [comment]
感谢反馈，此程序只在 ArchLinux，Windows 和 macOS 下测试过；会在下个 commit 修改为通过相对路径的读取 encrypt.js。
