### ISSUE TITLE
使用crontab不能正常运行login.py

### ISSUE THREAD

**Issue by huyonggang97** [kirainmoe/auto-daily-health-report#4]
报错如下：
Traceback (most recent call last):
  File "/root/auto-daily-health-report-master/app.py", line 47, in <module>
    res, sta = check_recent(username,
  File "/root/auto-daily-health-report-master/recent.py", line 36, in check_recent
    login(session, username, password, http_header, use_webvpn)
  File "/root/auto-daily-health-report-master/login.py", line 21, in login
    with open(r"./encrypt.js", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: './encrypt.js'

**Comment by kirainmoe** [comment]
请使用最新的 master 分支代码再试一次。

**Comment by huyonggang97** [comment]
谢谢~能正常使用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kirainmoe/auto-daily-health-report"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 下午5:30
***@***.***&gt;;
抄送:&nbsp;"Hu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [kirainmoe/auto-daily-health-report] 使用crontab不能正常运行login.py (#4)





 
请使用最新的 master 分支代码再试一次。
